package apply

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/davesade/kilolock/internal/slice"
)

// setupResult bundles everything the orchestrator needs after the
// apply tmp directory is materialized: the directory path itself
// and a cleanup function to be deferred.
type setupResult struct {
	Dir            string
	PluginCacheDir string
	Cleanup        func()
}

// setupApplyDir creates a tmp directory containing the operator's
// HCL minus any backend.tf, a synthetic backend.tf pinning the
// local backend, and a `terraform.tfstate` slice computed from
// trunk.
//
// The cleanup function in the returned setupResult is always safe
// to call (idempotent) and is what the caller defers. When
// skipCleanup is true, the function is a no-op so operators
// debugging a failure can poke at the directory afterward — the
// path is logged regardless.
func setupApplyDir(srcDir string, sliceState *slice.TrunkState, skipCleanup bool) (*setupResult, error) {
	if srcDir == "" {
		return nil, fmt.Errorf("setupApplyDir: srcDir is empty")
	}
	if sliceState == nil {
		return nil, fmt.Errorf("setupApplyDir: sliceState is nil")
	}

	dir, err := os.MkdirTemp("", "kl-apply-*")
	if err != nil {
		return nil, fmt.Errorf("mkdir tmp: %w", err)
	}

	cleanup := func() { _ = os.RemoveAll(dir) }
	if skipCleanup {
		cleanup = func() {}
	}

	// Recursively copy the operator's HCL tree, including local
	// sub-modules referenced by source = "./modules/foo". The
	// recursive walker skips a small denylist so the apply tmp dir
	// stays hermetic from the operator's backend cache:
	//
	//   - .terraform/ at any depth (rebuilt by `terraform init`
	//     inside the tmp dir; the operator's HTTP-backend cache is
	//     incompatible with our local backend)
	//   - .terraform.lock.hcl is preserved so the tmp apply uses the
	//     same provider selections as the operator's real workspace.
	//     This avoids silently drifting to newer provider versions
	//     during orchestrated apply.
	//   - terraform.tfstate / .backup at any depth (slice replaces
	//     the top-level one; nested ones come from sub-projects we
	//     don't own and shouldn't copy)
	//   - the top-level backend.tf (we synthesize the local-backend
	//     replacement below). Sub-module backend.tf is preserved if
	//     it exists, but Terraform itself rejects backend blocks in
	//     non-root modules so this is a no-op in practice.
	//   - hidden files / dirs (".something") to avoid copying
	//     editor/version-control crud.
	if err := copyHCLTree(srcDir, dir); err != nil {
		cleanup()
		return nil, fmt.Errorf("copy hcl: %w", err)
	}

	// Overwrite/synthesize backend.tf with an explicit local backend.
	// Even if the operator's HCL had no backend.tf, terraform's
	// default-backend behavior is local but the explicit form
	// documents the intent for anyone inspecting the tmp dir.
	const localBackend = `# auto-generated by kl apply
# replaces the operator's backend with a local one so terraform
# plans / applies against the orchestrator's slice in this dir.
terraform {
  backend "local" {}
}
`
	backendPath := filepath.Join(dir, "backend.tf")
	if err := os.WriteFile(backendPath, []byte(localBackend), 0o644); err != nil {
		cleanup()
		return nil, fmt.Errorf("write backend.tf: %w", err)
	}

	// Write the slice as terraform.tfstate.
	sliceBytes, err := slice.MarshalTrunkState(sliceState)
	if err != nil {
		cleanup()
		return nil, fmt.Errorf("marshal slice: %w", err)
	}
	statePath := filepath.Join(dir, "terraform.tfstate")
	if err := os.WriteFile(statePath, sliceBytes, 0o644); err != nil {
		cleanup()
		return nil, fmt.Errorf("write slice tfstate: %w", err)
	}

	pluginCacheDir := filepath.Join(dir, ".kl-plugin-cache")
	if err := os.MkdirAll(pluginCacheDir, 0o755); err != nil {
		cleanup()
		return nil, fmt.Errorf("mkdir plugin cache dir: %w", err)
	}

	return &setupResult{
		Dir:            dir,
		PluginCacheDir: pluginCacheDir,
		Cleanup:        cleanup,
	}, nil
}

// copyHCLTree recursively copies src into dst, applying the deny
// rules documented in setupApplyDir. Directories are mkdir'd as
// needed; files are streamed through copyOneFile.
//
// The top-level backend.tf is skipped (we synthesize it). Inside
// sub-modules a backend.tf is kept verbatim — terraform itself
// will reject backend blocks in non-root modules, so the file
// either was never valid or the operator already removed it.
func copyHCLTree(src, dst string) error {
	return copyHCLTreeAt(src, dst, true)
}

// copyHCLTreeAt is the recursive worker. isRoot=true triggers the
// "skip top-level backend.tf" rule; nested calls pass false so a
// sub-module's backend.tf (if any) is preserved.
func copyHCLTreeAt(src, dst string, isRoot bool) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		return fmt.Errorf("read dir %s: %w", src, err)
	}
	for _, e := range entries {
		name := e.Name()
		if shouldSkipEntry(e, name, isRoot) {
			continue
		}
		srcPath := filepath.Join(src, name)
		dstPath := filepath.Join(dst, name)
		if e.IsDir() {
			if err := os.MkdirAll(dstPath, 0o755); err != nil {
				return fmt.Errorf("mkdir %s: %w", dstPath, err)
			}
			if err := copyHCLTreeAt(srcPath, dstPath, false); err != nil {
				return err
			}
			continue
		}
		if err := copyOneFile(srcPath, dstPath); err != nil {
			return fmt.Errorf("copy %s: %w", name, err)
		}
	}
	return nil
}

// shouldSkipEntry decides whether a directory entry should be
// excluded from the apply tmp dir.
//
// isRoot selects the stricter top-level ruleset (skip the
// operator's backend.tf and any top-level terraform.tfstate
// because we synthesize them). Inside sub-modules the same rules
// don't apply — Terraform tolerates a backend.tf inside a module
// as a no-op, and a nested terraform.tfstate is foreign data we shouldn't
// second-guess.
func shouldSkipEntry(e os.DirEntry, name string, isRoot bool) bool {
	if strings.HasPrefix(name, ".") {
		// .terraform/, hidden editor files, .git, etc. — never
		// useful inside the apply tmp dir.
		return true
	}
	if isRoot {
		switch name {
		case "backend.tf",
			"terraform.tfstate",
			"terraform.tfstate.backup":
			return true
		}
	}
	return false
}

func copyOneFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}
